Modules/data analytics SRS introduction
thoth-tech/documentation pull request #114
Opened 2022-08-09 07:56 UTC by GaganSinghGit

# Description

Data analytics SRS introduction

Fixes # (issue)

## Type of change

- [ ] Documentation (update or new)

2022-08-12 01:32 UTC, Zephreo commented
You need to run prettier on the file:
- Open the documentation folder in your terminal (that has npm installed)
- `npm install`
- `npm run format`
- `npm run lint`
- Commit changes

2022-08-12 01:34 UTC, Zephreo requested changes
You need to run prettier on the file:
- Open the documentation folder in your terminal (that has npm installed)
- `npm install`
- `npm run format`
- `npm run lint`
- Commit changes

Otherwise drop me or Tim a message if you need help setting that up

2022-08-17 01:41 UTC, timmydzeko requested changes

2022-08-17 01:41 UTC, timmydzeko commented on docs/Splashkit/Modules/Data Analytics/Software_Requirements_Specification.md
> +- Dataset: A collection of data in tabular form. fFiles ending in comma separated values (.csv), tab
Need to remove lowercase f from beginning of `Files` on line 34

2022-08-17 01:41 UTC, timmydzeko commented on docs/Splashkit/Modules/Data Analytics/Software_Requirements_Specification.md
> +  separated values (.tbv), Excel (.xlsx) file extension.
Add .txt files as an option as well

2022-08-29 06:31 UTC, Zephreo requested changes

2022-08-29 06:31 UTC, Zephreo commented on docs/Splashkit/Modules/Data Analytics/Software_Requirements_Specification.md
> +pre-process the data for use in machine learning model.
```suggestion
The purpose of Data Analytics module is that it is a tool that allows users to import, create data
visualisations, and use pre-written algorithms to perform statistical analysis of the data, and
pre-process data for use in a machine learning model.
```

2022-08-29 06:31 UTC, Zephreo commented on docs/Splashkit/Modules/Data Analytics/Software_Requirements_Specification.md
> +The intended audience is Data Analysts, Machine Learning Engineer and developer.
```suggestion
The intended audience is Data Analysts, Machine Learning Engineers, and developers.
```

2022-08-29 06:31 UTC, Zephreo commented on docs/Splashkit/Modules/Data Analytics/Software_Requirements_Specification.md
> +in a machine learning model.
```suggestion
The intended use of this module is to create data visualisations and preprocess the data to be used
in a machine learning model.
```
Needs check from Tim about ML models here.

2022-08-29 06:31 UTC, Zephreo commented on docs/Splashkit/Modules/Data Analytics/Software_Requirements_Specification.md
> +- Create data visualisations like bar graphs, histograms.
```suggestion
- Create dataframes by importing datasets. Adding and removing rows/columns in a dataset.
- Changing data inside a dataset.
- Preprocessing functionality for cleaning and standardising the dataframe for the goal of making it
  fit to be used in a machine learning model.
- Create data visualisations like bar graphs, histograms.
```

2022-08-29 06:31 UTC, Zephreo commented on docs/Splashkit/Modules/Data Analytics/Software_Requirements_Specification.md
> +  analyse it
```suggestion
- Dataset: A collection of data in tabular form. Files ending in comma separated values (.csv), tab
  separated values (.tbv), Excel (.xlsx), test (.txt) file extension.
- Dataframe: Representation of dataset as an object in the program which allows users to use method
  calls to perform actions on the dataset.
- Standardising: the process of converting data to a common format to enable users to process and
  analyse it
```

2022-08-29 07:25 UTC, Zephreo approved these changes
I don't see any glaring issues, am happy for merge after tim checks.

2022-08-31 10:35 UTC, timmydzeko approved these changes

2022-08-31 11:00 UTC, timmydzeko commented
@GaganSinghGit The conflict is that the file location has been changed. Needs to be committed into a folder called Background inside the Data Analytics folder. This should fix the merge conflict

2022-09-02 09:48 UTC, Zephreo commented
just resolved conflict, sory

2022-09-02 09:57 UTC, merged