Informations about Frontend Migration
thoth-tech/documentation pull request #145
Opened 2022-09-24 06:23 UTC by lst97

Add information migration progress.

_Any italic text should be deleted from the final Pull Request text, including this line_

# Description

_Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change._

Fixes # (issue)

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (update or new)

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration_

## Testing Checklist:

- [ ] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

2022-09-24 06:27 UTC, lst97 reviewed
Initial pull request
Waiting for video to be upload
Some link may need to change.

2022-09-24 06:35 UTC, lst97 reviewed
Fix indentation in syntax.coffee

2022-09-24 08:54 UTC, lst97 reviewed
commented for linelint check.

2022-09-24 08:58 UTC, lst97 commented
Hey @leocomsci I need your help to solve the Linelint error
[EOF Rule] File "docs/Company Operations/Company Documentation Team/# Password Guideline.md" has lint errors
[EOF Rule] File "docs/OnTrack/Front End Migration/Code References/CoffeeScript/syntax.coffee" has lint errors

2022-09-26 09:52 UTC, leocomsci commented
HI @lst97 , there is a template that you can follow in order to generate a documentation. I attached this link below: 
https://github.com/thoth-tech/documentation/blob/main/docs/OnTrack/Documentation/OnTrack%20Documentation%20Template.md

2022-09-26 10:27 UTC, leocomsci commented
Don't forget to add @ShaeChristmas  as a reviewer

2022-09-26 10:33 UTC, leocomsci commented on docs/OnTrack/Front End Migration/Code References/CoffeeScript/syntax.coffee
> +# # 1. Variables and Scope
Those documentation are same as what we did in our team channel. We already asked Nelson to add the Documentation Template to make this documentation make more sense. This is good to me. @ShaeChristmas @Ishrat420 Is there anything that I and Nelson should consider or fix? 
- Moreover, It seems that there is an error relating to linelint in check section of this PR. I have no idea about that error. Let me know if you have any ideas

2022-09-28 05:21 UTC, ShaeChristmas approved these changes
Everything looked good to me, just make sure that the md files pass the prettier and vale checks.

2022-09-28 05:23 UTC, ShaeChristmas requested changes
Please ensure that Vale and Prettier checks succeed

2022-11-22 06:19 UTC, lst97 commented
@ShaeChristmas @Ishrat420 @leocomsci Check PASSED, please check.

2022-12-13 02:39 UTC, merged