ontrack-enhance the chart
thoth-tech/documentation pull request #188
Opened 2022-12-26 08:02 UTC by nicole5311

# Description

including two figma page, technical diagram and angular jason.

2022-12-26 08:47 UTC, lst97 requested changes
1. I can see your team submit different design and Figma, in this case, can you create a folder that use your name as parent folder name or use "design 1", "design 2" to separate you team design, so that it will not confuse future student. 

2. In the UML diagram, what is the diagram for? DB, Workflow or the Application, It is recommend that you should included a document to explain the diagram.

3. Same for the above comment, should include document about the diagram, shows why you design the diagram this way.

Thank you.

2022-12-26 08:47 UTC, lst97 commented on docs/OnTrack/Data Analytics Platform/angular.json
> +import { Component, VERSION } from '@angular/core';
This is a jsx file, this is not a valid json format. Also in this repo, we only need to upload documents not the code file. Please upload your code into your own repo and make a document here to link to your code repo. Thank you.

2022-12-26 08:47 UTC, lst97 commented on docs/OnTrack/Data Analytics Platform/Student progress overview.json
> +{"uuid":"f8c275c0-8454-11ed-ba80-5bcc15aa9607","page":{"id":115741619,"data":{"appState":"[\"~#iR\",[\"^ \",\"n\",\"appTemplate\",\"v\",[\"^ \",\"isFetching\",false,\"plugins\",[\"~#iOM\",[\"welcomeT
I think you will need to document the two code file shows how we can run your application, and what is this file for.

2023-03-09 10:26 UTC, maddernd commented
This one is being cancelled as it fails all checks.

2023-03-09 10:26 UTC, closed without merging