Software Requirements Specifications Document
thoth-tech/documentation pull request #25
Opened 2022-04-23 12:33 UTC by jctrainor

# Description

Due to the previous SRS that the deployment team made not being up to standard, I've made the necessary changes to the documentation, and now includes all the correct material 

## Type of change

- [X] Documentation (update or new)

# How Has This Been Tested?

I've tested the documentation in both Firefox and Chrome, and the documentation works as intended on both platforms. Later I will do testing on Safari to ensure that the documentation is working on all platforms

## Testing Checklist:

- [X] Tested in latest Chrome
- [ ] Tested in latest Safari
- [X] Tested in latest Firefox

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

2022-04-28 10:24 UTC, talzid commented
Is this intended as a draft still?

2022-05-03 07:59 UTC, ginge270 requested changes
Are you able to use the SRS template nad move the information you've created into that format?

https://github.com/thoth-tech/handbook/blob/main/docs/processes/quality-assurance/templates/srs-template.md

2022-05-10 11:45 UTC, talzid commented
Slight nudge @jctrainor

2022-05-21 05:40 UTC, ginge270 approved these changes

2022-05-23 04:48 UTC, merged