Included All Designs from Figma
thoth-tech/documentation pull request #373
Opened 2023-08-21 07:07 UTC by wmvoon

_Any italic text should be deleted from the final Pull Request text, including this line_

# Description

_Included Figma designs in this pull request. This inlcudes Analytics Page and Pop Up UI.
Link to Figma >>> https://www.figma.com/file/smb4NtanK3yvxyvcwZZaoz/Draft---CourseFlow?type=design&node-id=0%3A1&mode=design&t=ZuzWiSiZcvJmrXrf-1
A file of review about the previous designs is included as well. _

Fixes # (issue)

## Type of change

- Documentation (update or new)

2023-08-22 23:40 UTC, maddernd commented
This needs converting to markdown, not PDF.

2023-08-22 23:41 UTC, maddernd requested changes
Please adjust this to be in a markdown format.

2023-08-23 00:49 UTC, wmvoon commented
Added the markdown format report, removed the pdf file

2023-08-27 05:38 UTC, maddernd approved these changes

2023-08-27 22:36 UTC, merged