Review On Mouse Inputs Functionality Guide
thoth-tech/documentation pull request #541
Opened 2024-08-29 01:42 UTC by s223126445

Review documentation for Tutorial on Mouse Inputs Functionality Guide
The Introduction to Mouse Inputs Functionality Guide in SplashKit tutorial is checked the python and C++ are working without any errors.
Making sure that all C# Code follows top-level statements and made the changes fixed the mouse location functionality error in C# and minor changes to the text to make the content and code more coherent. This document covers all the checks and links to the PR for this audit.

2024-08-30 23:39 UTC, breezy-codes requested changes

2024-08-30 23:39 UTC, breezy-codes commented on docs/Splashkit/Tutorials/Reviews/Review On Mouse Inputs Functionality Guide.md
> +- Fixed the Code error of Mouse Location Functionality Mouse x in C#.
I would move this up into the description, as this section is more so for "future" improvements.

2024-08-30 23:40 UTC, breezy-codes commented
Good tutorial review, and great work on this doc. Just one small change requested

2024-10-21 03:21 UTC, omckeon approved these changes

2024-10-21 03:22 UTC, merged