Jplag docs
thoth-tech/documentation pull request #555
Opened 2024-09-19 12:57 UTC by atharv02-git

# Description

This update builds on Jack's work on the JPlag Feasibility document. Specifically, I created a prototype in Figma, which helped us identify the best location for positioning the "Download JPlag Report" button in the frontend. Additionally, I updated the feasibility document to include: 

- A new image showcasing the updated frontend layout with the "Download JPlag Report" button.
- Detailed documentation explaining the frontend integration of JPlag, including how the JPlag report will be generated, visualized, and made accessible to users.

## Prototype

Below is my prototype created in Figma:
![figma frontend](https://github.com/user-attachments/assets/5f343f02-ac74-4d01-aa9a-7f8b9e03ca80)

## Type of change

- [ ] Documentation (update)

# Checklist:

- [ ] I have made corresponding changes to the documentation

2024-09-21 06:18 UTC, JackSCarroll requested changes

2024-09-21 06:18 UTC, JackSCarroll commented on docs/OnTrack/JPlag/Jplag-Feasibility-Document.md
> +If you login as admin or convenor, navigate to any unit > Inbox > Explorer > goto any of student submission, currently you will find a "View Similarities" button for the MOSS plagiarism detection rep
`currently you will find a "View Similarities" button for the MOSS plagiarism detection report. We aim to extend this functionality to include JPlag. To achieve this, we plan to embed the JPlag report viewer into this section for seamless integration. The report generated by JPlag, available in a zip file format, will be processed and displayed in a readable format similar to the existing MOSS reports.`
This is outdated now, please remove.

2024-09-21 06:18 UTC, JackSCarroll commented on docs/OnTrack/JPlag/Jplag-Feasibility-Document.md
> +We have created a button labeled "Download JPLAG Report," which can be seen in the below UI; positioned next to the "View Similarities" button, allowing the teaching staff to download the detailed JP
`We have created a button labeled "Download JPLAG Report," which can be seen in the below UI; positioned next to the "View Similarities" button, allowing the teaching staff to download the detailed JPLAG analysis. `
This is also outdated

2024-09-21 06:18 UTC, JackSCarroll commented on docs/OnTrack/JPlag/Jplag-Feasibility-Document.md
> +- Author(s): Jack Carroll
Add your name too

2024-09-23 23:42 UTC, atharv02-git commented
Hey Jack, thanks for the review, all the necessary changes has been addressed now, please have a look and let me know 😊

2025-03-25 22:37 UTC, closed without merging