Grade Icon Migration Documentation
thoth-tech/documentation pull request #561
Opened 2024-11-12 02:25 UTC by Shounaks

# Description
Added Migration Guide for `grade-icon` component.

## Type of change
- [x] Documentation (new)

# How Has This Been Tested?
## Testing Checklist:

- [x] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have requested a review from ... on the Pull Request

2024-11-12 11:18 UTC, Ashdeore commented on docs/OnTrack/UI Enhancement/Component Reviews/grade-icon.md
Hiii, I have noticed that the component only displays for users with 'Tutor' permissions. Are there any other conditions under which this component is hidden?

2024-11-12 11:28 UTC, Ashdeore commented on docs/OnTrack/UI Enhancement/Component Reviews/grade-icon.md
All done, thank you.

2024-11-13 03:18 UTC, Ashdeore approved these changes
Approved! The code appears to be well-written, and the components align effectively with the proposed specifications. The documentation is thorough and clearly presented. Great job!

![5](https://github.com/user-attachments/assets/f43d6814-a67c-4702-afd6-d6ca1128e85c)

![1](https://github.com/user-attachments/assets/161697e6-0a78-4439-9ec7-d47021466529)

![2](https://github.com/user-attachments/assets/939afbea-087f-43e9-b683-cdc2511aedb1)

![3](https://github.com/user-attachments/assets/69905cd3-7df3-4c4f-83b2-39dca747107e)

![4](https://github.com/user-attachments/assets/8a703d2d-5bce-459f-a9e3-b4c1a4d323c8)

2024-11-13 03:25 UTC, s223552468 approved these changes
Approved! I’ve reviewed the proposed changes and can confirm that the grade-icon component is utilized as intended. I also logged into Ontrack using the tutor credentials, as only they have access to the grade-icon. The component appears consistent in its usage within Ontrack as well. One suggestion: we could consider adding more detailed documentation to enhance clarity.

![#561](https://github.com/user-attachments/assets/33ed3e1d-ac43-4397-b138-19b006f7186c)

![Screenshot 2024-11-13 142336](https://github.com/user-attachments/assets/a0c6fc3b-1a85-4b7a-867e-aecef3dbe296)

2024-11-18 01:34 UTC, satikaj requested changes

2024-11-18 01:34 UTC, satikaj commented on docs/OnTrack/UI Enhancement/Component Reviews/grade-icon.md
> +This item, can only be seen on screens with Tutor or higher permissions.
I don't think only tutors can see it. A student can as well through screens like the portfolio submission screen. Please make sure to identify all uses of grade-icon in the code to be safe. You can search 'grade-icon' in VS Code and see every mention of it in the repo.

2025-01-20 12:03 UTC, satikaj approved these changes

2025-01-20 12:03 UTC, merged